version: '3'

services:
  # Node.js application service
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - redis

  # MongoDB service
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  # Redis service
  redis:
    image: redis
    ports:
      - 6379:6379

# Define a volume for MongoDB data persistence
volumes:
  mongodb_data:
